### ISSUE TITLE
Generate only unique graphs

### ISSUE THREAD

**Issue by thedrow** [pckroon/hypothesis-networkx#11]
When running in debug mode I often get the following:
```
Trying example: test_execution_order_with_dependend_step(steps_dependency_graph=
Nodes: [0, 1]
Edges: [(0, 1)]
```

I'd rather tests only unique graphs if possible.

**Comment by pckroon** [comment]
What's your exact invocation of `graph_builder`? These could be different in their node/edge attributes.
Also, this would be more of an `hypothesis` issue rather than a `hypothesis-networkx` issue. Especially since `graph_builder` only ever constructs a single graph at the time, I have no control over whether I produce duplicate items.

**Comment by thedrow** [comment]
```python
class DebuggableDiGraph(DiGraph):
    def __repr__(self):
        return f"""
Nodes: {self.nodes}
Edges: {self.edges}
        """

    def __eq__(self, other):
        return self.nodes == other.nodes and self.edges == other.edges

steps_dependency_graph_builder = graph_builder(
    graph_type=DebuggableDiGraph,
    min_nodes=1,
    max_nodes=50,
    min_edges=0,
    self_loops=False,
    connected=True,
).filter(lambda g: is_directed_acyclic_graph(g))
```

**Comment by pckroon** [comment]
It could also be due to how Hypothesis shrinks the graphs maybe. Whatever graph you shrink at some point you'll pass `Nodes: [0, 1]; Edges: [(0, 1)]`.
Either way, there's not really anything I can do about this.

**Comment by thedrow** [comment]
I think there is, we can maintain a list of graphs and check if a graph is isomorphic.
Let me draft a PR and see what happens.

**Comment by thedrow** [comment]
```python
previous_graphs = []

@given(steps_dependency_graph=steps_dependency_graph_builder)
@settings(
    suppress_health_check=(HealthCheck.too_slow,),
    max_examples=500,
    deadline=1200000,
)
def test_execution_order(steps_dependency_graph, request):
    g = steps_dependency_graph.copy()
    global previous_graphs
    assume(not any(is_isomorphic(g, G) for G in previous_graphs))
    previous_graphs.append(g)
```

works just fine.
If we want to implement it ourselves we need to maintain state somehow.

**Comment by thedrow** [comment]
It works on the first run but not on the second since the test results are inconsistent...
